//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SySDEAProject.ConsultarAeronauta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AeronautaParametro", Namespace="http://schemas.datacontract.org/2004/07/ANAC.SICO.Ws.DataTypes")]
    [System.SerializableAttribute()]
    public partial class AeronautaParametro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CdAnacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdAeronautaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeAeronautaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeSistemaAutenticacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeSistemaRequisitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCpfField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CdAnac {
            get {
                return this.CdAnacField;
            }
            set {
                if ((object.ReferenceEquals(this.CdAnacField, value) != true)) {
                    this.CdAnacField = value;
                    this.RaisePropertyChanged("CdAnac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdAeronauta {
            get {
                return this.IdAeronautaField;
            }
            set {
                if ((this.IdAeronautaField.Equals(value) != true)) {
                    this.IdAeronautaField = value;
                    this.RaisePropertyChanged("IdAeronauta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginSistema {
            get {
                return this.LoginSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginSistemaField, value) != true)) {
                    this.LoginSistemaField = value;
                    this.RaisePropertyChanged("LoginSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeAeronauta {
            get {
                return this.NomeAeronautaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeAeronautaField, value) != true)) {
                    this.NomeAeronautaField = value;
                    this.RaisePropertyChanged("NomeAeronauta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeSistemaAutenticacao {
            get {
                return this.NomeSistemaAutenticacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeSistemaAutenticacaoField, value) != true)) {
                    this.NomeSistemaAutenticacaoField = value;
                    this.RaisePropertyChanged("NomeSistemaAutenticacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeSistemaRequisitante {
            get {
                return this.NomeSistemaRequisitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeSistemaRequisitanteField, value) != true)) {
                    this.NomeSistemaRequisitanteField = value;
                    this.RaisePropertyChanged("NomeSistemaRequisitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCpf {
            get {
                return this.NumeroCpfField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCpfField, value) != true)) {
                    this.NumeroCpfField = value;
                    this.RaisePropertyChanged("NumeroCpf");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AeronautaType", Namespace="http://schemas.datacontract.org/2004/07/ANAC.SICO.Ws.DataTypes")]
    [System.SerializableAttribute()]
    public partial class AeronautaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CdAnacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CdCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CdCctField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertMilitarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SySDEAProject.ConsultarAeronauta.EnderecoAeronautaType[] EnderecosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SySDEAProject.ConsultarAeronauta.EnderecoEletronicoAeronautaType[] EnderecosEletronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdAeronautaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAeronaveganteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NacionalidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeAeronautaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroIdentidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTituloEleitorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroZonaTituloEleitorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgaoCertMilitarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SgEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SgUfNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SgUfTituloEleitorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StFalecidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SySDEAProject.ConsultarAeronauta.TelefoneAeronautaType[] TelefonesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEscolaridadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoSanguineoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoSexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CdAnac {
            get {
                return this.CdAnacField;
            }
            set {
                if ((object.ReferenceEquals(this.CdAnacField, value) != true)) {
                    this.CdAnacField = value;
                    this.RaisePropertyChanged("CdAnac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CdCategoria {
            get {
                return this.CdCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CdCategoriaField, value) != true)) {
                    this.CdCategoriaField = value;
                    this.RaisePropertyChanged("CdCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CdCct {
            get {
                return this.CdCctField;
            }
            set {
                if ((object.ReferenceEquals(this.CdCctField, value) != true)) {
                    this.CdCctField = value;
                    this.RaisePropertyChanged("CdCct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CertMilitar {
            get {
                return this.CertMilitarField;
            }
            set {
                if ((object.ReferenceEquals(this.CertMilitarField, value) != true)) {
                    this.CertMilitarField = value;
                    this.RaisePropertyChanged("CertMilitar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SySDEAProject.ConsultarAeronauta.EnderecoAeronautaType[] Enderecos {
            get {
                return this.EnderecosField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecosField, value) != true)) {
                    this.EnderecosField = value;
                    this.RaisePropertyChanged("Enderecos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SySDEAProject.ConsultarAeronauta.EnderecoEletronicoAeronautaType[] EnderecosEletronico {
            get {
                return this.EnderecosEletronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecosEletronicoField, value) != true)) {
                    this.EnderecosEletronicoField = value;
                    this.RaisePropertyChanged("EnderecosEletronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public long IdAeronauta {
            get {
                return this.IdAeronautaField;
            }
            set {
                if ((this.IdAeronautaField.Equals(value) != true)) {
                    this.IdAeronautaField = value;
                    this.RaisePropertyChanged("IdAeronauta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int IdAeronavegante {
            get {
                return this.IdAeronaveganteField;
            }
            set {
                if ((this.IdAeronaveganteField.Equals(value) != true)) {
                    this.IdAeronaveganteField = value;
                    this.RaisePropertyChanged("IdAeronavegante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nacionalidade {
            get {
                return this.NacionalidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.NacionalidadeField, value) != true)) {
                    this.NacionalidadeField = value;
                    this.RaisePropertyChanged("Nacionalidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime Nascimento {
            get {
                return this.NascimentoField;
            }
            set {
                if ((this.NascimentoField.Equals(value) != true)) {
                    this.NascimentoField = value;
                    this.RaisePropertyChanged("Nascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomeAeronauta {
            get {
                return this.NomeAeronautaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeAeronautaField, value) != true)) {
                    this.NomeAeronautaField = value;
                    this.RaisePropertyChanged("NomeAeronauta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NumeroCpf {
            get {
                return this.NumeroCpfField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCpfField, value) != true)) {
                    this.NumeroCpfField = value;
                    this.RaisePropertyChanged("NumeroCpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NumeroIdentidade {
            get {
                return this.NumeroIdentidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroIdentidadeField, value) != true)) {
                    this.NumeroIdentidadeField = value;
                    this.RaisePropertyChanged("NumeroIdentidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NumeroTituloEleitor {
            get {
                return this.NumeroTituloEleitorField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTituloEleitorField, value) != true)) {
                    this.NumeroTituloEleitorField = value;
                    this.RaisePropertyChanged("NumeroTituloEleitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NumeroZonaTituloEleitor {
            get {
                return this.NumeroZonaTituloEleitorField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroZonaTituloEleitorField, value) != true)) {
                    this.NumeroZonaTituloEleitorField = value;
                    this.RaisePropertyChanged("NumeroZonaTituloEleitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Orgao {
            get {
                return this.OrgaoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgaoField, value) != true)) {
                    this.OrgaoField = value;
                    this.RaisePropertyChanged("Orgao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OrgaoCertMilitar {
            get {
                return this.OrgaoCertMilitarField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgaoCertMilitarField, value) != true)) {
                    this.OrgaoCertMilitarField = value;
                    this.RaisePropertyChanged("OrgaoCertMilitar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SgEmpresa {
            get {
                return this.SgEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.SgEmpresaField, value) != true)) {
                    this.SgEmpresaField = value;
                    this.RaisePropertyChanged("SgEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SgUfNascimento {
            get {
                return this.SgUfNascimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.SgUfNascimentoField, value) != true)) {
                    this.SgUfNascimentoField = value;
                    this.RaisePropertyChanged("SgUfNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SgUfTituloEleitor {
            get {
                return this.SgUfTituloEleitorField;
            }
            set {
                if ((object.ReferenceEquals(this.SgUfTituloEleitorField, value) != true)) {
                    this.SgUfTituloEleitorField = value;
                    this.RaisePropertyChanged("SgUfTituloEleitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StFalecido {
            get {
                return this.StFalecidoField;
            }
            set {
                if ((object.ReferenceEquals(this.StFalecidoField, value) != true)) {
                    this.StFalecidoField = value;
                    this.RaisePropertyChanged("StFalecido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SySDEAProject.ConsultarAeronauta.TelefoneAeronautaType[] Telefones {
            get {
                return this.TelefonesField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonesField, value) != true)) {
                    this.TelefonesField = value;
                    this.RaisePropertyChanged("Telefones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TipoEscolaridade {
            get {
                return this.TipoEscolaridadeField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEscolaridadeField, value) != true)) {
                    this.TipoEscolaridadeField = value;
                    this.RaisePropertyChanged("TipoEscolaridade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TipoSanguineo {
            get {
                return this.TipoSanguineoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoSanguineoField, value) != true)) {
                    this.TipoSanguineoField = value;
                    this.RaisePropertyChanged("TipoSanguineo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TipoSexo {
            get {
                return this.TipoSexoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoSexoField, value) != true)) {
                    this.TipoSexoField = value;
                    this.RaisePropertyChanged("TipoSexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnderecoAeronautaType", Namespace="http://schemas.datacontract.org/2004/07/ANAC.SICO.Ws.DataTypes")]
    [System.SerializableAttribute()]
    public partial class EnderecoAeronautaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CdCepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroEnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SgUfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEnderecoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CdCep {
            get {
                return this.CdCepField;
            }
            set {
                if ((object.ReferenceEquals(this.CdCepField, value) != true)) {
                    this.CdCepField = value;
                    this.RaisePropertyChanged("CdCep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Logradouro {
            get {
                return this.LogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroField, value) != true)) {
                    this.LogradouroField = value;
                    this.RaisePropertyChanged("Logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int NumeroEndereco {
            get {
                return this.NumeroEnderecoField;
            }
            set {
                if ((this.NumeroEnderecoField.Equals(value) != true)) {
                    this.NumeroEnderecoField = value;
                    this.RaisePropertyChanged("NumeroEndereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SgUf {
            get {
                return this.SgUfField;
            }
            set {
                if ((object.ReferenceEquals(this.SgUfField, value) != true)) {
                    this.SgUfField = value;
                    this.RaisePropertyChanged("SgUf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TipoEndereco {
            get {
                return this.TipoEnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEnderecoField, value) != true)) {
                    this.TipoEnderecoField = value;
                    this.RaisePropertyChanged("TipoEndereco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnderecoEletronicoAeronautaType", Namespace="http://schemas.datacontract.org/2004/07/ANAC.SICO.Ws.DataTypes")]
    [System.SerializableAttribute()]
    public partial class EnderecoEletronicoAeronautaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoEletronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StEmailDcertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEnderecoEletronicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EnderecoEletronico {
            get {
                return this.EnderecoEletronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoEletronicoField, value) != true)) {
                    this.EnderecoEletronicoField = value;
                    this.RaisePropertyChanged("EnderecoEletronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StEmailDcerta {
            get {
                return this.StEmailDcertaField;
            }
            set {
                if ((object.ReferenceEquals(this.StEmailDcertaField, value) != true)) {
                    this.StEmailDcertaField = value;
                    this.RaisePropertyChanged("StEmailDcerta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TipoEnderecoEletronico {
            get {
                return this.TipoEnderecoEletronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEnderecoEletronicoField, value) != true)) {
                    this.TipoEnderecoEletronicoField = value;
                    this.RaisePropertyChanged("TipoEnderecoEletronico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelefoneAeronautaType", Namespace="http://schemas.datacontract.org/2004/07/ANAC.SICO.Ws.DataTypes")]
    [System.SerializableAttribute()]
    public partial class TelefoneAeronautaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoTelefoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NumeroTelefone {
            get {
                return this.NumeroTelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTelefoneField, value) != true)) {
                    this.NumeroTelefoneField = value;
                    this.RaisePropertyChanged("NumeroTelefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TipoTelefone {
            get {
                return this.TipoTelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoTelefoneField, value) != true)) {
                    this.TipoTelefoneField = value;
                    this.RaisePropertyChanged("TipoTelefone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsultarAeronauta.IAeronautaService")]
    public interface IAeronautaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeronautaService/ConsultarAeronauta", ReplyAction="http://tempuri.org/IAeronautaService/ConsultarAeronautaResponse")]
        SySDEAProject.ConsultarAeronauta.AeronautaType[] ConsultarAeronauta(SySDEAProject.ConsultarAeronauta.AeronautaParametro aeronauta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeronautaService/ConsultarAeronauta", ReplyAction="http://tempuri.org/IAeronautaService/ConsultarAeronautaResponse")]
        System.Threading.Tasks.Task<SySDEAProject.ConsultarAeronauta.AeronautaType[]> ConsultarAeronautaAsync(SySDEAProject.ConsultarAeronauta.AeronautaParametro aeronauta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAeronautaServiceChannel : SySDEAProject.ConsultarAeronauta.IAeronautaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AeronautaServiceClient : System.ServiceModel.ClientBase<SySDEAProject.ConsultarAeronauta.IAeronautaService>, SySDEAProject.ConsultarAeronauta.IAeronautaService {
        
        public AeronautaServiceClient() {
        }
        
        public AeronautaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AeronautaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AeronautaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AeronautaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SySDEAProject.ConsultarAeronauta.AeronautaType[] ConsultarAeronauta(SySDEAProject.ConsultarAeronauta.AeronautaParametro aeronauta) {
            return base.Channel.ConsultarAeronauta(aeronauta);
        }
        
        public System.Threading.Tasks.Task<SySDEAProject.ConsultarAeronauta.AeronautaType[]> ConsultarAeronautaAsync(SySDEAProject.ConsultarAeronauta.AeronautaParametro aeronauta) {
            return base.Channel.ConsultarAeronautaAsync(aeronauta);
        }
    }
}
